### ISSUE TITLE
user.dart is incorrect

### ISSUE THREAD

**Issue by festelo** [stablekernel/aqueduct_examples#1]
I have error when I try to repeat the sample:
![image](https://user-images.githubusercontent.com/20724864/40008076-198ed5bc-57a7-11e8-9386-b968a783413c.png)

Dart version 2.0.0-dev.54.0.flutter-e6d7d67f4b

**Comment by joeconwaystk** [comment]
Thanks. Aqueduct 2 is not compatible with Dart 2. Aqueduct 3 is. There is a 3.0 branch in this repository with the changes required to run with Dart 2. This branch will be merged to master with Dart2/Aqueduct3 are released.

The current version of Dart 2 SDK has a few blocking issues to fully support Aqueduct 3, but they are being worked on.
