### ISSUE TITLE
Examples have path dependencies that seem to be specific to 'Users/joeconway/Projects/'

### ISSUE THREAD

**Issue by jarrodcolburn** [stablekernel/aqueduct_examples#10]
https://github.com/stablekernel/aqueduct_examples/blob/4e7d960e3f45ff7839d49767ee688fe218c13971/heroes/pubspec.yaml#L16-L19

Should dependency overrides be removed? This tripped me up for a minute when I got errors that the location did not exist on my machine. I get why the overrides are there, but for people going through the tutorial, the errors might scare them away from what looks to be a great tool.

**Comment by jairoFernandez** [comment]
Please create a PR for this :pray:  @JarrodCColburn

**Comment by jarrodcolburn** [comment]
What Dart Environment Version should it be linked to? ...and Aqueduct?
Last I tried, I was getting errors from breaking changes on Dart 2.8.

**Comment by jarrodcolburn** [comment]
see pr https://github.com/stablekernel/aqueduct_examples/pull/11
