### ISSUE TITLE
Can not run flutter todo App.

### ISSUE THREAD

**Issue by uwejan** [stablekernel/aqueduct_examples#3]
Hello there,
This could not be an issue with code rather could be my knowledge less in dart, However, While running the todo flutter app, register new user, i get error exception;
```
D/EGL_emulation( 5368): eglMakeCurrent: 0xaa9b2040: ver 2 0 (tinfo 0xa1403320)
E/flutter ( 5368): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 5368): type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>'
E/flutter ( 5368): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
E/flutter ( 5368): #1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 5368): #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
What should i do make it work?
Thanks.

**Comment by uwejan** [comment]
Awesome now it works, Thank you.
I wish to take the opportunity and ask this, now with todo_app flutter, how can i make user forgot password/ change password.

**Comment by joeconwaystk** [comment]
This is now merged to master 👍

**Comment by sudolibre** [comment]
> I wish to take the opportunity and ask this, now with todo_app flutter, how can i make user forgot password/ change password.

Hi @uwejan , first off thanks for reporting this issue and your interest in aqueduct. In regards to the forgot password implementation you're more likely to get the discussion you're looking for in the slack channel: http://slackaqueductsignup.herokuapp.com.
